UNAVAILABLE_STATUS_CODE = 503
UNAVAILABLE_MESSAGE = 'Service Unavailable'
INTERNAL_SERVER_ERROR_MESSAGE = 'internal server error'
DEFAULT_RESPONSE = {'message': 'ok'}
STATUS_FORCE_LIST = [429, 500, 502, 503, 504]
