UNAVAILABLE_STATUS_CODE = 503
UNAVAILABLE_MESSAGE = 'Service Unavailable'
INTERNAL_SERVER_ERROR_MESSAGE = 'internal server error'
DEFAULT_RESPONSE = {'message': 'ok'}
STATUS_FORCE_LIST = [429, 500, 502, 503, 504]
UNPROCESSABLE_ENTITY_CODE = 422
UNPROCESSABLE_ENTITY_MESSAGE = 'Unprocessable Entity'
