name: Run Google Login Using Selenium

on:
  workflow_dispatch:
    inputs:
        user_email:
          description: 'User Email'
          type: environment
          required: true
        user_password:
          description: 'User Password'
          type: environment
          required: true
        login_url:
          description: 'Login URL'
          type: environment
          required: true
        success_url:
          description: 'Success URL'
          type: environment
          required: true

jobs:
  google-auth-test:
    name: Google Auth Using Selenium
    runs-on: ubuntu-latest
    env:
      LOGIN_URL: ${{ github.event.inputs.login_url }}
      USER_EMAIL: ${{ github.event.inputs.user_email }}
      USER_PASSWORD: ${{ github.event.inputs.user_password }}
      SUCCESS_URL: ${{ github.event.inputs.success_url }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: |
          requirements/requirements.txt
    - name: Instanll dev dependencies
      run: |
        pip install pip-tools==6.9.0
        pip-sync requirements/requirements.txt
    - name: Test Google Login Using Selenium
      run: |
        python main.py
